def get_headers() -> dict:
    return {
        "accept": "*/*",
        "accept-language": "en-US,en;q=0.9",
        "content-type": "application/x-www-form-urlencoded;charset=UTF-8",
        "priority": "u=1, i",
        "sec-ch-ua": "\"Not_A Brand\";v=\"99\", \"Chromium\";v=\"142\"",
        "sec-ch-ua-arch": "\"\"",
        "sec-ch-ua-bitness": "\"\"",
        "sec-ch-ua-form-factors": "",
        "sec-ch-ua-full-version": "\"\"",
        "sec-ch-ua-full-version-list": "",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-model": "\"\"",
        "sec-ch-ua-platform": "\"Linux\"",
        "sec-ch-ua-platform-version": "\"\"",
        "sec-ch-ua-wow64": "?0",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "x-client-data": "CI7cygE=",
        "x-goog-visitor-id": "COrD1N-s5doCFYv85QYdLw",   
        "x-goog-ext-525001261-jspb": "[1,null,null,null,\"9ec249fc9ad08861\",null,null,0,[4]]",
        "x-goog-ext-73010989-jspb": "[0]",
        "x-same-domain": "1",
        "referer": "https://gemini.google.com/",
    }
